// // Generated by Xata Codegen 0.29.2. Please do not edit.
// import { buildClient } from "@xata.io/client";
// import type {
//   BaseClientOptions,
//   SchemaInference,
//   XataRecord,
// } from "@xata.io/client";

// const tables = [
//   { name: "folder", columns: [{ name: "name", type: "string", unique: true }] },
// ] as const;

// export type SchemaTables = typeof tables;
// export type InferredTypes = SchemaInference<SchemaTables>;

// export type Folder = InferredTypes["folder"];
// export type FolderRecord = Folder & XataRecord;

// export type DatabaseSchema = {
//   folder: FolderRecord;
// };

// const DatabaseClient = buildClient();

// const defaultOptions = {
//   databaseURL:
//     "https://Shambhav-Shandilya-s-workspace-t085bb.us-east-1.xata.sh/db/test-auth-db",
// };

// export class XataClient extends DatabaseClient<DatabaseSchema> {
//   constructor(options?: BaseClientOptions) {
//     super({ ...defaultOptions, ...options }, tables);
//   }
// }

// let instance: XataClient | undefined = undefined;

// export const getXataClient = () => {
//   if (instance) return instance;

//   instance = new XataClient();
//   return instance;
// };
